#include <pebble.h>

typedef struct {
  const char *slug;
  uint32_t black;
  uint32_t white;
} HabitIconResource;

static const HabitIconResource s_habit_icon_resources[] = {
  {"art", RESOURCE_ID_HABIT_ICON_ART, RESOURCE_ID_HABIT_ICON_ART_W},
  {"baseball", RESOURCE_ID_HABIT_ICON_BASEBALL, RESOURCE_ID_HABIT_ICON_BASEBALL_W},
  {"basketball", RESOURCE_ID_HABIT_ICON_BASKETBALL, RESOURCE_ID_HABIT_ICON_BASKETBALL_W},
  {"bed", RESOURCE_ID_HABIT_ICON_BED, RESOURCE_ID_HABIT_ICON_BED_W},
  {"bicycle", RESOURCE_ID_HABIT_ICON_BICYCLE, RESOURCE_ID_HABIT_ICON_BICYCLE_W},
  {"brain", RESOURCE_ID_HABIT_ICON_BRAIN, RESOURCE_ID_HABIT_ICON_BRAIN_W},
  {"breathe", RESOURCE_ID_HABIT_ICON_BREATHE, RESOURCE_ID_HABIT_ICON_BREATHE_W},
  {"camera", RESOURCE_ID_HABIT_ICON_CAMERA, RESOURCE_ID_HABIT_ICON_CAMERA_W},
  {"cat", RESOURCE_ID_HABIT_ICON_CAT, RESOURCE_ID_HABIT_ICON_CAT_W},
  {"church", RESOURCE_ID_HABIT_ICON_CHURCH, RESOURCE_ID_HABIT_ICON_CHURCH_W},
  {"clean", RESOURCE_ID_HABIT_ICON_CLEAN, RESOURCE_ID_HABIT_ICON_CLEAN_W},
  {"cook", RESOURCE_ID_HABIT_ICON_COOK, RESOURCE_ID_HABIT_ICON_COOK_W},
  {"dog", RESOURCE_ID_HABIT_ICON_DOG, RESOURCE_ID_HABIT_ICON_DOG_W},
  {"drink", RESOURCE_ID_HABIT_ICON_DRINK, RESOURCE_ID_HABIT_ICON_DRINK_W},
  {"football", RESOURCE_ID_HABIT_ICON_FOOTBALL, RESOURCE_ID_HABIT_ICON_FOOTBALL_W},
  {"fruit", RESOURCE_ID_HABIT_ICON_FRUIT, RESOURCE_ID_HABIT_ICON_FRUIT_W},
  {"game", RESOURCE_ID_HABIT_ICON_GAME, RESOURCE_ID_HABIT_ICON_GAME_W},
  {"garden", RESOURCE_ID_HABIT_ICON_GARDEN, RESOURCE_ID_HABIT_ICON_GARDEN_W},
  {"guitar", RESOURCE_ID_HABIT_ICON_GUITAR, RESOURCE_ID_HABIT_ICON_GUITAR_W},
  {"heart", RESOURCE_ID_HABIT_ICON_HEART, RESOURCE_ID_HABIT_ICON_HEART_W},
  {"heat", RESOURCE_ID_HABIT_ICON_HEAT, RESOURCE_ID_HABIT_ICON_HEAT_W},
  {"hydrate", RESOURCE_ID_HABIT_ICON_HYDRATE, RESOURCE_ID_HABIT_ICON_HYDRATE_W},
  {"ice", RESOURCE_ID_HABIT_ICON_ICE, RESOURCE_ID_HABIT_ICON_ICE_W},
  {"lotus", RESOURCE_ID_HABIT_ICON_LOTUS, RESOURCE_ID_HABIT_ICON_LOTUS_W},
  {"meditate", RESOURCE_ID_HABIT_ICON_MEDITATE, RESOURCE_ID_HABIT_ICON_MEDITATE_W},
  {"money", RESOURCE_ID_HABIT_ICON_MONEY, RESOURCE_ID_HABIT_ICON_MONEY_W},
  {"music", RESOURCE_ID_HABIT_ICON_MUSIC, RESOURCE_ID_HABIT_ICON_MUSIC_W},
  {"piano", RESOURCE_ID_HABIT_ICON_PIANO, RESOURCE_ID_HABIT_ICON_PIANO_W},
  {"pill", RESOURCE_ID_HABIT_ICON_PILL, RESOURCE_ID_HABIT_ICON_PILL_W},
  {"plant", RESOURCE_ID_HABIT_ICON_PLANT, RESOURCE_ID_HABIT_ICON_PLANT_W},
  {"read", RESOURCE_ID_HABIT_ICON_READ, RESOURCE_ID_HABIT_ICON_READ_W},
  {"run", RESOURCE_ID_HABIT_ICON_RUN, RESOURCE_ID_HABIT_ICON_RUN_W},
  {"smoke", RESOURCE_ID_HABIT_ICON_SMOKE, RESOURCE_ID_HABIT_ICON_SMOKE_W},
  {"soccer", RESOURCE_ID_HABIT_ICON_SOCCER, RESOURCE_ID_HABIT_ICON_SOCCER_W},
  {"star", RESOURCE_ID_HABIT_ICON_STAR, RESOURCE_ID_HABIT_ICON_STAR_W},
  {"study", RESOURCE_ID_HABIT_ICON_STUDY, RESOURCE_ID_HABIT_ICON_STUDY_W},
  {"swim", RESOURCE_ID_HABIT_ICON_SWIM, RESOURCE_ID_HABIT_ICON_SWIM_W},
  {"tea", RESOURCE_ID_HABIT_ICON_TEA, RESOURCE_ID_HABIT_ICON_TEA_W},
  {"toothbrush", RESOURCE_ID_HABIT_ICON_TOOTHBRUSH, RESOURCE_ID_HABIT_ICON_TOOTHBRUSH_W},
  {"tree", RESOURCE_ID_HABIT_ICON_TREE, RESOURCE_ID_HABIT_ICON_TREE_W},
  {"tv", RESOURCE_ID_HABIT_ICON_TV, RESOURCE_ID_HABIT_ICON_TV_W},
  {"vegetable", RESOURCE_ID_HABIT_ICON_VEGETABLE, RESOURCE_ID_HABIT_ICON_VEGETABLE_W},
  {"walk", RESOURCE_ID_HABIT_ICON_WALK, RESOURCE_ID_HABIT_ICON_WALK_W},
  {"water", RESOURCE_ID_HABIT_ICON_WATER, RESOURCE_ID_HABIT_ICON_WATER_W},
  {"weights", RESOURCE_ID_HABIT_ICON_WEIGHTS, RESOURCE_ID_HABIT_ICON_WEIGHTS_W},
  {"write", RESOURCE_ID_HABIT_ICON_WRITE, RESOURCE_ID_HABIT_ICON_WRITE_W},
  {"yoga", RESOURCE_ID_HABIT_ICON_YOGA, RESOURCE_ID_HABIT_ICON_YOGA_W},
  {"default", RESOURCE_ID_HABIT_ICON_DEFAULT, RESOURCE_ID_HABIT_ICON_DEFAULT_W},
};

#define HABIT_ICON_RESOURCE_COUNT 48

uint32_t habit_icon_resource_for_slug(const char *slug, bool white) {
  for (int i = 0; i < HABIT_ICON_RESOURCE_COUNT; i++) {
    if (strcmp(slug, s_habit_icon_resources[i].slug) == 0) {
      return white ? s_habit_icon_resources[i].white : s_habit_icon_resources[i].black;
    }
  }
  return white ? RESOURCE_ID_HABIT_ICON_DEFAULT_W : RESOURCE_ID_HABIT_ICON_DEFAULT;
}
